services:
  api:
    build: ./backend
    container_name: evaluacion_fede_api
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CORS_ORIGINS: ${CORS_ORIGINS}
    volumes:
      - ./backend:/app
      - ./.env:/app/.env:ro
    ports:
      - "8004:8000"

  frontend:
    build: ./frontend
    container_name: evaluacion_fede_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    ports:
      - "5174:5173"
